### ISSUE TITLE
Monthly Updates

### ISSUE THREAD

**Issue by 112523chen** [112523chen/112523chen.github.io#20]
**Description:** Tasks required to maintain the website

**Tasks:**
- [ ] Update content if need
- [ ] Add new content if need
- [ ] Add newest public resume if need

**Comment by 112523chen** [comment]
nice
