### ISSUE TITLE
Monthly Update: June23

### ISSUE THREAD

**Issue by 112523chen** [112523chen/112523chen.github.io#29]
**Description:** Tasks required to maintain the website

**Tasks:**
- [ ] Update content if need
- [ ] Add new content if need
- [ ] Add newest public resume if need
