### ISSUE TITLE
Monthly Update: December 23

### ISSUE THREAD

**Issue by 112523chen** [112523chen/112523chen.github.io#50]
**Description:** Tasks required to maintain the website

**Tasks:**
- [x] Update content if need
- [x] Add new content if need
- [x] Add newest public resume if need
